services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    volumes:
      - ./data/drone-server:/data
    environment:
      DRONE_GITEA_SERVER: ${DRONE_GITEA_SERVER}
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_USER_CREATE: username:${DRONE_USER_CREATE_NAME},admin:true
      DRONE_GITEA_SKIP_VERIFY: ${DRONE_GITEA_SKIP_VERIFY}
    restart: always
    networks:
      - infra

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone-server
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone-server
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: runner-1
      DRONE_RUNNER_VOLUMES: /var/run/docker.sock:/var/run/docker.sock,${INFRA_PATH}:/root/infrastructure
    volumes:
      - ./data/drone-runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - infra

networks:
  infra:
    external: true
