services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__server__ROOT_URL: ${GITEA_ROOT_URL}
      GITEA__server__SSH_PORT: ${GITEA_SSH_PORT}
      GITEA__server__HTTP_PORT: ${GITEA_HTTP_PORT}
      GITEA__webhook__ALLOWED_HOST_LIST: ${GITEA_WEBHOOK_ALLOWED_HOSTS}
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    networks:
      - infra
    restart: always

networks:
  infra:
    external: true
