services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${INFRA_PATH}/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${INFRA_PATH}/nginx/conf.d/gitea.conf:/etc/nginx/conf.d/gitea.conf:ro
      - ${INFRA_PATH}/nginx/conf.d/drone.conf:/etc/nginx/conf.d/drone.conf:ro
      - ${INFRA_PATH}/nginx/conf.d/registry.conf:/etc/nginx/conf.d/registry.conf:ro
      - ${INFRA_PATH}/nginx/data/certs:/etc/nginx/certs:ro
      - ${INFRA_PATH}/nginx/data/logs:/var/log/nginx
    networks:
      infra:
        aliases:
          - ${DOMAIN_GITEA}
          - ${DOMAIN_DRONE}
          - ${DOMAIN_REGISTRY}

networks:
  infra:
    external: true
